### PR TITLE
Add a 'See more' button to the end of the results list, or infinite scrolling of list #34

### PR DESCRIPTION
**Pull request by getinnocuous**
I've created a generic button type for internal and external links, kept it static for now as I'm not sure how the new data is going to be fetched. I've also moved results mode into the constants so there aren't lots of strings being checked

### CODE REVIEW

**Comment by tomoakley** [comment]
thanks @getinnocuous 🎉 Will merge this but right now our priority is implementing the new design. If you're able to do some more on this today, shoot me an email or Twitter DM (link in readme) and I'll send you an invite

**Comment by tomoakley** [comment]
I can't see the show more link at the bottom of the list...I think it's being hidden due to overflow issue. Would you be ok to fix it? Thanks

**Comment by getinnocuous** [comment]
is it worth closing this PR as the new design make it redundant now?

**Comment by tomoakley** [comment]
Hey @getinnocuous - the new design has been merged. But I don't think that makes this redundant - a See more link would still be useful. So if you wanted to fix this up, that'd be great

**Pull request closed without merging**
