### PR TITLE
Resolves #9 - Adds Offline/PWA Support

### LINKED ISSUE #9: Add offline support and/or PWA integration
Would be really cool to have offline support for this. A lot of the people who are gonna be using it may not have a constant wifi/data connection so it would be good if they could use it even when offline. If it could be saved to a mobile homescreen and act like a Progressive Web App that'd be fantastic.

### PR DESCRIPTION
**Pull request by marktdodds**

### CODE REVIEW

**Comment by marktdodds** [comment]
Ideally if we could get some people on various devices (iOS + Android) to test it by adding to homescreen and turning off their wifi/data that would be great. Build preview is here: https://deploy-preview-25--hardcore-euler-a92447.netlify.app/

**Comment by tomoakley** [comment]
This is working for me from my homescreen with data off 🎉  iPhone 6s iOS 14

**Comment by marktdodds** [comment]
Can you check the scrolling as well. There were issues earlier but I think it was related to caching old files.

**Comment by marktdodds** [comment]
@tomoakley ready to be approved and merged

**Review by tomoakley — APPROVED** [review]

**Pull request merged**
